#!/bin/sh

dotnet build --no-restore || {
  echo "Build failed. Fix compilation errors before pushing."
  exit 1
}

dotnet test --no-restore || {
  echo "Tests failed. Fix code before pushing."
  exit 1
}
